### PR TITLE
Fix fixed boards double render

### LINKED ISSUE #1868: Grid “blink” when `order` and `items` update separately in GridBase.js
## Description
When `GridBase` receives its props as separate updates—first a new `order`, then a new `items` array—it runs its internal [`sortGrid`](https://github.com/cboard-org/cboard/blob/1313d8d8cb058727f96c8ae7b38c11564ba78f74/src/components/FixedGrid/GridBase.js#L28) twice That results in two back-to-back renders and a visible “blink” as the grid reflows from the old state to the in-between state, then to the final state.

## Video

https://github.com/user-attachments/assets/82063a81-3643-40a9-9693-0ee65ad09ffe

### PR DESCRIPTION
**Pull request by RodriSanchez1**
close #1868

### CODE REVIEW

File: src/components/FixedGrid/GridBase.js [hunk 1]
```diff
@@ -7,25 +7,33 @@ import Row from './Row/Row';
...
   const gridClassName = classNames(styles.root, className);
 
-  const grid = utils.sortGrid({ columns, rows, order, items });
+  const grid = useMemo(
+    () => {
+      console.log('REmemoized');
+      return utils.sortGrid({ columns, rows, order, items });
+    },
+    [columns, rows, order, items]
+  );
```
Comment (RodriSanchez1) [inline src/components/FixedGrid/GridBase.js]: This `useMemo`  is not working as expected because the `gridState` is defined on the `Board.component` as an inline component. It gets recreated when the BoardComponent is rendered. The memozation of this `gridState` is not avaible beacuse `Board` is a class componente and the hook `useMemo` is not avaliable´.  @tomivm @shayc  @gonojuarez what do you think?

File: src/components/FixedGrid/Grid.js [hunk 2]
```diff
@@ -23,23 +23,23 @@ const focusPosition = {
...
     className,
-    items,
     style,
     setIsScroll,
     fixedRef,
     isBigScrollBtns,
     isNavigationButtonsOnTheSide,
+    gridState,
     ...other
   } = props;
```
Comment (tomivm) [inline src/components/FixedGrid/Grid.js:35]: We can add ` const { items } = gridState;` and avoid lot of changes in this file

File: src/components/FixedGrid/GridBase.js (hunk 1 above)
Comment (tomivm) [reply src/components/FixedGrid/GridBase.js]: Do you think this change is necessary in this PR? I think that we can treat it separately and merge this PR without inconvenience.
Let me know!

File: src/components/FixedGrid/Grid.js (hunk 2 above)
Comment (RodriSanchez1) [reply src/components/FixedGrid/Grid.js:35]: Yeah! Good idea

File: src/components/FixedGrid/GridBase.js (hunk 1 above)
Comment (RodriSanchez1) [reply src/components/FixedGrid/GridBase.js]: We can leave this to other PR where we improve the grid performance. I will create a new issue to remember to work on this

Comment (RodriSanchez1) [reply src/components/FixedGrid/GridBase.js]: Anyway, I tested it without `useMemo` and noticed more re-renders than when we use `useMemo`, so I’ll leave it.

Comment (tomivm) [reply src/components/FixedGrid/GridBase.js]: Fine Rodri!! 🚀

**Review by tomivm — APPROVED** [review]
Awesome Job @RodriSanchez1 🚀
