### PR TITLE
Fix ElevenLabs voices ordering in Voices list

### LINKED ISSUE #2040: ElevenLabs voices listed in wrong order in Voices list
## Description

Currently, **ElevenLabs voices** are displayed **after** the online voices in the voices list.
The correct order should be:

1. **Local TTS voices**
2. **ElevenLabs voices**
3. **Online voices**

This order ensures that ElevenLabs voices appear right after local voices, making them easier for users to find and select.

---

## 🧩 Steps to Reproduce

1. Open **Settings → Speech**.
2. Open the **Voices** dropdown list.
3. Observe the order in which voices are displayed.

---

## ✅ Expected Behavior

The voices list should follow this order:

1. Local TTS voices
2. ElevenLabs voices
3. Online voices

---

## ❌ Actual Behavior

ElevenLabs voices are listed **after** the online voices instead of immediately following local TTS voices.

---

## 🧪 Environment

* **App version:** `v1.38.0` (current)
* **Platform:** Web / Android / iOS / Windows
* **Browser:** Chrome / Edge / Safari / Firefox

---

## 📝 Additional Notes

* This issue affects the usability and discoverability of ElevenLabs voices.
* Correcting the sorting order improves UX consistency and aligns with the intended hierarchy of voice sources.

---

### PR DESCRIPTION
**Pull request by sharan-deep21**
Description:
This change ensures ElevenLabs voices are listed immediately after local TTS voices, before online/cloud voices, in the Voices dropdown. This improves discoverability and UX consistency.

close #2040

### CODE REVIEW

**Comment by RodriSanchez1** [comment]
Hello @sharan-deep21 ! Thanks for your PR. Please remove the `package-lock.json` and `yarn.lock` files as there is  is no  updates or added package in the PR?

**Comment by sharan-deep21** [comment]
> Hello @sharan-deep21 ! Thanks for your PR. Please remove the `package-lock.json` and `yarn.lock` files as there is is no updates or added package in the PR?

Removed package-lock.json and yarn.lock as requested. CI is now failing because yarn.lock is expected in the pipeline config. Should I restore yarn.lock or will the pipeline be updated

**Comment by RodriSanchez1** [comment]
Yes! Sorry for the confusion. You should not remove the files you should not add changes on them for this PR. Just leave the changes for the `tts.js` file

**Comment by sharan-deep21** [comment]
> Yes! Sorry for the confusion. You should not remove the files you should not add changes on them for this PR. Just leave the changes for the `tts.js` file

sorry for that! 😅 Now once check this.

**Comment by magush27** [comment]
@sharan-deep21 I was reviewing your PR and its ok, but I found there is a little inconsistency between the main path for the voices and the other locations. I mean in this lines in the same function they still have the previous order:
```
  // Line 206 - Wrong order (cloudVoices before elevenLabsVoices)
  resolve(cloudVoices.concat(elevenLabsVoices));
```
```
  // Line 211
  resolve(platformVoices.concat(cloudVoices).concat(elevenLabsVoices));
```
```
  // Line 216
  resolve(platformVoices.concat(cloudVoices).concat(elevenLabsVoices));
```

They should be:

```
  // Line 206
  resolve(elevenLabsVoices.concat(cloudVoices));
```
```
  // Line 211
  resolve(platformVoices.concat(elevenLabsVoices).concat(cloudVoices));
```
```
  // Line 216
  resolve(platformVoices.concat(elevenLabsVoices).concat(cloudVoices));
```

Also, there is a repetitive logic there in the concatenation that you can refactor with a helper function like this to combine the voices:

```
async getVoices() {
    let cloudVoices = [];
    let elevenLabsVoices = [];

    // Helper function to combine voices in consistent order
    const combineVoices = (platform, elevenlabs, cloud) =>
      platform.concat(elevenlabs).concat(cloud);

    return new Promise((resolve, reject) => {
      platformVoices = this._getPlatformVoices() || [];

      if (platformVoices.length) {
        resolve(combineVoices(platformVoices, elevenLabsVoices, cloudVoices));
      }

      // Android
      if ('onvoiceschanged' in synth) {
        synth.addEventListener('voiceschanged', function voiceslst() {
          const voices = synth.getVoices();
          synth.removeEventListener('voiceschanged', voiceslst);

          if (!voices || voices.length === 0) {
            resolve(combineVoices([], elevenLabsVoices, cloudVoices));
            return null;
          }

          platformVoices = voices._list || voices;
          resolve(combineVoices(platformVoices, elevenLabsVoices, cloudVoices));
        });
      } else if (isCordova()) {
        // Samsung devices on Cordova
        platformVoices = this._getPlatformVoices();
        resolve(combineVoices(platformVoices, elevenLabsVoices, cloudVoices));
      }
    });
  }
```

**Comment by sharan-deep21** [comment]
> @sharan-deep21 I was reviewing your PR and its ok, but I found there is a little inconsistency between the main path for the voices and the other locations. I mean in this lines in the same function they still have the previous order:
> 
> ```
>   // Line 206 - Wrong order (cloudVoices before elevenLabsVoices)
>   resolve(cloudVoices.concat(elevenLabsVoices));
> ```
> 
> ```
>   // Line 211
>   resolve(platformVoices.concat(cloudVoices).concat(elevenLabsVoices));
> ```
> 
> ```
>   // Line 216
>   resolve(platformVoices.concat(cloudVoices).concat(elevenLabsVoices));
> ```
> 
> They should be:
> 
> ```
>   // Line 206
>   resolve(elevenLabsVoices.concat(cloudVoices));
> ```
> 
> ```
>   // Line 211
>   resolve(platformVoices.concat(elevenLabsVoices).concat(cloudVoices));
> ```
> 
> ```
>   // Line 216
>   resolve(platformVoices.concat(elevenLabsVoices).concat(cloudVoices));
> ```
> 
> Also, there is a repetitive logic there in the concatenation that you can refactor with a helper function like this to combine the voices:
> 
> ```
> async getVoices() {
>     let cloudVoices = [];
>     let elevenLabsVoices = [];
> 
>     // Helper function to combine voices in consistent order
>     const combineVoices = (platform, elevenlabs, cloud) =>
>       platform.concat(elevenlabs).concat(cloud);
> 
>     return new Promise((resolve, reject) => {
>       platformVoices = this._getPlatformVoices() || [];
> 
>       if (platformVoices.length) {
>         resolve(combineVoices(platformVoices, elevenLabsVoices, cloudVoices));
>       }
> 
>       // Android
>       if ('onvoiceschanged' in synth) {
>         synth.addEventListener('voiceschanged', function voiceslst() {
>           const voices = synth.getVoices();
>           synth.removeEventListener('voiceschanged', voiceslst);
> 
>           if (!voices || voices.length === 0) {
>             resolve(combineVoices([], elevenLabsVoices, cloudVoices));
>             return null;
>           }
> 
>           platformVoices = voices._list || voices;
>           resolve(combineVoices(platformVoices, elevenLabsVoices, cloudVoices));
>         });
>       } else if (isCordova()) {
>         // Samsung devices on Cordova
>         platformVoices = this._getPlatformVoices();
>         resolve(combineVoices(platformVoices, elevenLabsVoices, cloudVoices));
>       }
>     });
>   }
> ```

yeah ive fixed it ✔ if any further changes have to be done please mention it 😊

**Review by magush27 — APPROVED** [review]
Now its ok, great job!

File: src/providers/SpeechProvider/tts.js [hunk 1]
```diff
@@ -211,21 +200,20 @@ const tts = {
       if ('onvoiceschanged' in synth) {
         synth.addEventListener('voiceschanged', function voiceslst() {
           const voices = synth.getVoices();
-          if (!voices.length) {
+          synth.removeEventListener('voiceschanged', voiceslst);
+
+          if (!voices || voices.length === 0) {
+            resolve(elevenLabsVoices.concat(cloudVoices));
             return null;
```
Comment (RodriSanchez1) [inline src/providers/SpeechProvider/tts.js:207]: I think that we can remove the `return null` as the promise is being resolved before calling it 

what do you think @magush27

Comment (magush27) [reply src/providers/SpeechProvider/tts.js:207]: yes! I think is a good idea as the return null there is redundant and the code will be cleaner

Comment (RodriSanchez1) [reply src/providers/SpeechProvider/tts.js:207]: @sharan-deep21 Could you make the changes? If not let my know and I will do it
