### PR TITLE
Fix memory leak and improve image fetching in Symbol component

### LINKED ISSUE #1900: Symbols images URLs are not being cleaned on component unmount
This can generate memory leaks

### LINKED ISSUE #1901: Refactor Symbol component
Should: 

- Handle errors on indexed db call and image retrival
- Improve the useEffect block to use early returns
- Add a cancelled state that should avoid state changes when the component is unmounted preventing warnings

### PR DESCRIPTION
**Pull request by RodriSanchez1**
See first the  #1898 

Address memory leak by revoking object URLs in the cleanup function and streamline image fetching from the indexed DB. Remove unnecessary dependencies from the useEffect hook and improve code legibility using early returns.

close #1901
close #1900

### CODE REVIEW

File: src/components/Board/Symbol/Symbol.js [hunk 1]
```diff
@@ -43,27 +43,62 @@ function Symbol(props) {
   } = props;
 
   const [src, setSrc] = useState(image ? formatSrc(image) : '');
+  const objectUrlRef = useRef(null);
+
+  const fetchArasaacImage = useCallback(async id => {
```
Comment (tomivm) [inline src/components/Board/Symbol/Symbol.js]: We can name it with something similar to`fetchArasaacImagefromIndexedDB` or `fetchLocalArasaacImage`

File: src/components/Board/Symbol/Symbol.js [hunk 2]
```diff
@@ -43,27 +43,62 @@ function Symbol(props) {
...
-          const blob = new Blob([image.data], { type: image.type });
-          setSrc(URL.createObjectURL(blob));
-        } else if (props.image) {
-          setSrc(formatSrc(props.image));
+          setSrc(formatSrc(image));
+          return;
         }
-      }
 
+        setSrc('');
```
Comment (tomivm) [inline src/components/Board/Symbol/Symbol.js:90]: this is necessary?

File: src/components/Board/Symbol/Symbol.js [hunk 3]
```diff
@@ -43,27 +43,62 @@ function Symbol(props) {
...
+      }
       getSrc();
+
+      // Cleanup function
+      return () => {
+        cancelled = true;
```
Comment (tomivm) [inline src/components/Board/Symbol/Symbol.js:95]: Can you explain me why the cancelled is necessary?

File: src/components/Board/Symbol/Symbol.js [hunk 4]
```diff
@@ -43,27 +43,62 @@ function Symbol(props) {
...
+          setSrc(formatSrc(image));
+          return;
         }
-      }
 
+        setSrc('');
+      }
       getSrc();
+
+      // Cleanup function
```
Comment (tomivm) [inline src/components/Board/Symbol/Symbol.js]: remove comment please :)

**Review by tomivm — APPROVED** [review]
Looks good! We can think in remove the image from the useEffect dependencies. But maybe is better to do it in a next step to avoid edge cases for now

File: src/components/Board/Symbol/Symbol.js (hunk 2 above)
Comment (RodriSanchez1) [reply src/components/Board/Symbol/Symbol.js:90]: Is a fallback, if not an old image can be showed to the user and it can be confusing

File: src/components/Board/Symbol/Symbol.js (hunk 3 above)
Comment (RodriSanchez1) [reply src/components/Board/Symbol/Symbol.js:95]: This `cancelled` variable is neccesary to avoid changes in the component state if it was unmounted while an async function was performed.

**Comment by RodriSanchez1** [comment]
Thanks for the review! How do you think that we can remove the image from the dependecies? We need to manage the case when a tile have `image` and `local Arasaac image`

File: src/components/Board/Symbol/Symbol.js (hunk 3 above)
Comment (tomivm) [reply src/components/Board/Symbol/Symbol.js:95]: Fine thanks!

**Comment by tomivm** [comment]
Maybe we can consider show the local first if it is available. 
I think we can discuss it in another issue.
Awesome job!

**Comment by tomivm** [comment]
Sorry @RodriSanchez1 I miss that this branch is not pointing to the master branch. It's okey?

**Comment by RodriSanchez1** [comment]
It was a mistake! I just created a new PR to the master branch
