### PR TITLE
fix service worker, double mounting, and remove deprecated react lifecycle functions

### LINKED ISSUE #1153: WPA - Service Worker is not working
Service Worker is not installing in the web browser. Because of this, WPA is not available for download

### PR DESCRIPTION
**Pull request by martinbedouret**
This PR simplifies the logic for providers by fixing service worker, double mounting, and removing deprecated react lifecycle functions.

### CODE REVIEW

File: src/providers/SpeechProvider/SpeechProvider.container.js [hunk 1]
```diff
@@ -23,74 +22,46 @@ export class SpeechProvider extends Component {
   state = { voicesRecived: false };
```
Comment (tomivm) [inline src/providers/SpeechProvider/SpeechProvider.container.js]: this state is unnecessary

**Review by tomivm — APPROVED** [review]
Really good fix @martinbedouret

**Review by RodriSanchez1 — APPROVED** [review]
