### PR TITLE
bug/fix live mode clean output bar

### LINKED ISSUE #1050: the input for use the live feature is not available if the user clean de output bar.
imagen

### PR DESCRIPTION
**Pull request by RodriSanchez1**
close #1050

### CODE REVIEW

File: src/components/Board/Output/Output.container.js [hunk 1]
```diff
@@ -236,17 +238,26 @@ export class OutputContainer extends Component {
     }
   };
 
+  defaultLiveTile = {
+    backgroundColor: 'rgb(255, 241, 118)',
+    id: shortid.generate(),
```
Comment (martinbedouret) [inline src/components/Board/Output/Output.container.js]: it is not necessary now

**Review by martinbedouret — APPROVED** [review]
