### PR TITLE
fix: add id to created symbols

### LINKED ISSUE #47: After adding new symbols, selecting one of them select all the others
It happens because added symbols don't have ids so they all resolve to undefined and get selected.

### PR DESCRIPTION
**Pull request by ioRekz**
fixes #47

### CODE REVIEW

File: src/containers/Board/reducer.js [hunk 1]
```diff
@@ -20,7 +20,7 @@ function symbolReducer(board, action) {
   switch (action.type) {
     case ADD_SYMBOL:
       return Object.assign({}, board, {
-        symbols: [...board.symbols, action.symbol]
+        symbols: [...board.symbols, Object.assign({}, action.symbol, { id: board.symbols.length })]
```
Comment (shayc) [inline src/containers/Board/reducer.js:23]: Hey, good catch, I've been meaning to add unique ids, I will implement with this package: [shortid](https://www.npmjs.com/package/shortid) soon

**Review by shayc — APPROVED** [review]
thanks you!
