### PR TITLE
Electron input image fixed

### LINKED ISSUE #940: Cordova - Electron - Image doesnt load if user is not logged in
When you try to load an image to create a new folder or tile in electron app, its never showed. That problem only appears when the user is not logged in or doesnt have internet conection. 
 The bug is in the locally save method.

### PR DESCRIPTION
**Pull request by RodriSanchez1**
#940 
The load function in reader object was changed, to other one that have the same functionality and works with Electron.

### CODE REVIEW

File: src/components/UI/InputImage/InputImage.component.js [hunk 1]
```diff
@@ -34,13 +35,9 @@ class InputImage extends PureComponent {
...
-    reader.addEventListener(
-      'load',
-      () => {
-        this.props.onChange(reader.result);
-      },
-      false
-    );
+    reader.onload = () => {
+      this.props.onChange(reader.result);
+    };
```
Comment (martinbedouret) [inline src/components/UI/InputImage/InputImage.component.js:40]: @RodriSanchez1 Did you test this both for android and electron?

Comment (RodriSanchez1) [reply src/components/UI/InputImage/InputImage.component.js:40]: Yes, i did it in both platforms!
