### PR TITLE
Bug hue colour picker

### LINKED ISSUE #1864: bug: Hue color picker
The Colour picker option has problems in Android when users drag and drop it to choose a colour.

https://github.com/user-attachments/assets/ff466601-fe76-4c2c-9cfb-663ca06c300d

### PR DESCRIPTION
**Pull request by gonojuarez**
Solve the hue colour picker action when the user drags over the bar.
close #1864

### CODE REVIEW

File: src/components/Board/EditToolbar/EditToolbar.component.js [hunk 1]
```diff
@@ -75,10 +75,7 @@ EditToolbar.propTypes = {
    */
   onAddClick: PropTypes.func,
   onBoardTypeChange: PropTypes.func,
-  copiedTiles: PropTypes.arrayOf(PropTypes.object),
-  open: PropTypes.bool.isRequired,
-  onClose: PropTypes.func.isRequired,
-  onDialogAccecpted: PropTypes.func.isRequired
+  copiedTiles: PropTypes.arrayOf(PropTypes.object)
```
Comment (tomivm) [inline src/components/Board/EditToolbar/EditToolbar.component.js]: This change is not necessary

**Review by tomivm — CHANGES_REQUESTED** [review]
Hey Gonza! looks good! please review your enviroment because you are commiting the same change in all your PRs

**Review by tomivm — CHANGES_REQUESTED** [review]
Hey Gonza! looks good! please review your enviroment because you are commiting the same change in all your PRs

**Review by tomivm — APPROVED** [review]
