### PR TITLE
Fix/Output bar on Ios

### LINKED ISSUE #1397: Tiles on Output Bar are not sliding
When a tile is pressed, the output bar fills but does not slide.

### PR DESCRIPTION
**Pull request by tomivm**
In order to create a global solution for all browsers and user agents. This fix implements a new way to auto-scroll to the output bar's last symbol. 
close #1397

### CODE REVIEW

File: src/components/Board/Output/SymbolOutput/SymbolOutput.js [hunk 1]
```diff
@@ -54,6 +54,21 @@ class SymbolOutput extends PureComponent {
     symbols: []
   };
```
Comment (RodriSanchez1) [inline src/components/Board/Output/SymbolOutput/SymbolOutput.js:56]: Add The ` scrollToLastSymbol ` funtion on `componentDidMount()`

File: src/components/Board/Output/SymbolOutput/SymbolOutput.js [hunk 2]
```diff
@@ -54,6 +54,21 @@ class SymbolOutput extends PureComponent {
...
 
+  componentDidUpdate(prevProps) {
+    const scrollToLastSymbol = () => {
+      const { symbols } = this.props;
+      if (prevProps.symbols.length < symbols.length) {
+        try {
```
Comment (RodriSanchez1) [inline src/components/Board/Output/SymbolOutput/SymbolOutput.js]: @martinbedouret What do you think about use try catch block here?

File: src/components/Board/Output/SymbolOutput/Scroll/Scroll.js [hunk 3]
```diff
@@ -23,20 +21,16 @@ export class Scroll extends PureComponent {
       ...other
     } = this.props;
 
-    const scrollStyle = { direction: invertDir(direction) };
```
Comment (martinbedouret) [inline src/components/Board/Output/SymbolOutput/Scroll/Scroll.js:26]: invert the scroll direction is necessary in case of languages written from right to left (Arabic, Hebrew )

File: src/components/Board/Output/SymbolOutput/SymbolOutput.js (hunk 2 above)
Comment (martinbedouret) [reply src/components/Board/Output/SymbolOutput/SymbolOutput.js]: maybe necessary for the case that element is not found?

**Review by martinbedouret — CHANGES_REQUESTED** [review]

File: src/components/Board/Output/SymbolOutput/Scroll/Scroll.js (hunk 3 above)
Comment (tomivm) [reply src/components/Board/Output/SymbolOutput/Scroll/Scroll.js:26]: This is already contemplated on the Scroll__container. These lines were a part of the old way used to auto-scroll to the last element.

File: src/components/Board/Output/SymbolOutput/SymbolOutput.js (hunk 2 above)
Comment (tomivm) [reply src/components/Board/Output/SymbolOutput/SymbolOutput.js]: Yes. That was the intention.
