### PR TITLE
Quick fix for remove rows and columns function on fixed boards

### LINKED ISSUE #1109: Fixed board - Add or remove row or colum dont change grid order prop  correctly
When you add or remove a row or colum  on the fixed board, the grid order prop is not changed correctly. In the image, you can visualice the tiles position arent the same than the order displayed in the redux state.
image

### PR DESCRIPTION
**Pull request by tomivm**
Introduce a functions to chunk fixed boards efficiently while maintaining compatibility with deprecated chunking methods that cause 'order' issues when users removes columns or rows.
Now when we remove rows or columns the board conserve it's structure but remain filling empty spaces with tiles.
This is a quick fix until solve #1878
Close #1109

### CODE REVIEW

File: src/components/FixedGrid/utils.ts [hunk 1]
```diff
@@ -123,3 +124,50 @@ export function getNewOrder({ columns,
...
+  label?: string;
+  labelKey?: string;
+  vocalization?: string;
+  image: string;
+  loadBoard?: string;
+  sound?: string;
+  type?: string;
+  backgroundColor: string;
+  linkedBoard?: boolean;
+}
```
Comment (RodriSanchez1) [inline src/components/FixedGrid/utils.ts]: Relocate this interface to a new type file. As this it gonna be used across all the app across the progresive migration to TS

File: src/components/FixedGrid/utils.ts [hunk 2]
```diff
@@ -123,3 +124,50 @@ export function getNewOrder({ columns,
...
+
+export function compatibleDeprecatedChunks({ tileItems, order }:{
```
Comment (RodriSanchez1) [inline src/components/FixedGrid/utils.ts]: We should rename this function to be more descriptive as it return the ordered pages

File: src/components/FixedGrid/utils.ts [hunk 3]
```diff
@@ -123,3 +124,50 @@ export function getNewOrder({ columns,
...
+  tileItems: Array<TileItem>;
+  order: GridOrder;
+}):TileItem[][] {
+  const firstPageItemsInOrder = order.map(row =>
+    row.map(id => tileItems.find(item => item.id === id)||null)
+  );
```
Comment (RodriSanchez1) [inline src/components/FixedGrid/utils.ts]: Consider use a hash map to improve the performance of this operations and make it faster. Take a look on [js map](https://www.geeksforgeeks.org/javascript-map/) and [Hash Maps to Improve Time Complexity](https://javascript.plainenglish.io/hash-maps-to-improve-time-complexity-bc7ca692fcc) 

```js
const tileMap = new Map(tileItems.map(item => [item.id, item]));
const firstPageItemsInOrder = order.map(row =>
    row.map(id => tileMap.get(id) || null)
    );

```

File: src/components/FixedGrid/utils.ts [hunk 4]
```diff
@@ -123,3 +124,50 @@ export function getNewOrder({ columns,
...
+
+  const firstPage = lodash.flatten(firstPageItemsInOrder);
+  const unnorderedTiles = tileItems.filter(
```
Comment (RodriSanchez1) [inline src/components/FixedGrid/utils.ts]: Fix typo - `unorderedTiles`

File: src/components/FixedGrid/utils.ts [hunk 5]
```diff
@@ -123,3 +124,50 @@ export function getNewOrder({ columns,
...
+    item => !firstPage.find(tile => tile?.id === item.id)
+  );
+  const fillEmptyPositionsWithUnnorderedTilesForOldBoards = ({firstPageItemsInOrder,unnorderedTiles}:{firstPageItemsInOrder:(TileItem|null)[][],unnorderedTiles:Array<TileItem> }) => {
```
Comment (RodriSanchez1) [inline src/components/FixedGrid/utils.ts]: Fix typo `fillEmptyPositionsWithUnorderedTilesForOldBoards`

File: src/components/FixedGrid/utils.ts [hunk 6]
```diff
@@ -123,3 +124,50 @@ export function getNewOrder({ columns,
...
+
+export function compatibleDeprecatedChunks({ tileItems, order }:{
+  tileItems: Array<TileItem>;
+  order: GridOrder;
+}):TileItem[][] {
+  const firstPageItemsInOrder = order.map(row =>
+    row.map(id => tileItems.find(item => item.id === id)||null)
+  );
+
+  const firstPage = lodash.flatten(firstPageItemsInOrder);
```
Comment (RodriSanchez1) [inline src/components/FixedGrid/utils.ts]: Why dont you use the  [Array.prototype.flat()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat)?

File: src/components/FixedGrid/utils.ts [hunk 7]
```diff
@@ -123,3 +124,50 @@ export function getNewOrder({ columns,
...
+  const unnorderedTiles = tileItems.filter(
+    item => !firstPage.find(tile => tile?.id === item.id)
+  );
```
Comment (RodriSanchez1) [inline src/components/FixedGrid/utils.ts]: You can use the [Set ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) to save the ordered tile Ids and use it to find the unordered tiles faster 

```js
const orderedIds = new Set(order.flat()); // or you can do the new Set(firstPage.flaten())
const unorderedTiles = tileItems.filter(item => !orderedIds.has(item.id));
```

**Review by RodriSanchez1 — CHANGES_REQUESTED** [review]
Its a good idea to start refactoring the Fixed Grids. The `Grid` and the `Grid Base` can be merged in one file and we gonna have just one component that mange the grid render. 

What happens with the GridBase component if we merge this PR? I will recompute the Grid again within the sortGrid?

File: src/components/FixedGrid/utils.ts [hunk 8]
```diff
@@ -123,3 +124,50 @@ export function getNewOrder({ columns,
...
+  const fillEmptyPositionsWithUnnorderedTilesForOldBoards = ({firstPageItemsInOrder,unnorderedTiles}:{firstPageItemsInOrder:(TileItem|null)[][],unnorderedTiles:Array<TileItem> }) => {
+    let index = 0;
+    const deprecatedFirstPageItemsInOrder = firstPageItemsInOrder.map(row=>
+    row.map(item => {
+      if (item) return item;
+      index++;
+      return unnorderedTiles[index - 1]|| null;
+    }));
+    const deprecatedFirstPage = lodash.flatten(deprecatedFirstPageItemsInOrder).filter(item => item !== null);//
```
Comment (RodriSanchez1) [inline src/components/FixedGrid/utils.ts]: Consider using the Array.prototype.flat()

**Comment by RodriSanchez1** [comment]
Plese fix the [Codacy Static Code Analysis](https://github.com/cboard-org/cboard/pull/1891/checks?check_run_id=43150601881)

File: src/components/FixedGrid/utils.ts (hunk 6 above)
Comment (tomivm) [reply src/components/FixedGrid/utils.ts]: Because is experimental

File: src/components/FixedGrid/utils.ts (hunk 3 above)
Comment (tomivm) [reply src/components/FixedGrid/utils.ts]: Looks awesome but as is not a critical task I will create a ticket to give me time first to learn how to use it

File: src/components/FixedGrid/utils.ts (hunk 2 above)
Comment (tomivm) [reply src/components/FixedGrid/utils.ts]: Can you recommend a name please

**Comment by tomivm** [comment]
Hey @RodriSanchez1 
Thats is the plan :) Please for that. Can you please put more focus on the functionality and to review if we don't have differences between the new and the past behavior.
Next week I will focus on fix the typos and review your performance increase suggestion
My prettier is failing for this project in TS. Could you format the file to avoid the failing statics tests? 🔴

File: src/components/FixedGrid/utils.ts (hunk 6 above)
Comment (RodriSanchez1) [reply src/components/FixedGrid/utils.ts]: Not really [see compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat#browser_compatibility)

**Comment by RodriSanchez1** [comment]
> Its a good idea to start refactoring the Fixed Grids. The `Grid` and the `Grid Base` can be merged in one file and we gonna have just one component that mange the grid render.
> 
> What happens with the GridBase component if we merge this PR? I will recompute the Grid again within the sortGrid?

yeah, could you respond that?

The prettier is failing for me also. Is something on the TS config version and the file. We should fix this in the project

**Comment by tomivm** [comment]
Sorry I give you a more detailed explanation 💥 
Yes that is the plan! 
We gonna implement this in small steps focusing in Continues Integration.
The main Idea of this PR is to fix users intents that remove columns or rows, to not destroy his boards.
This is archived by refactoring a wrong chunk function that is cutting our pages only using the size of the board but ignoring the order. Also if we use only the order to separate pages, the tiles with not order (that is a bug that we have now in our board) are moved to the second page but it causes changes in how users with bugged boards are seeing his tiles.
For that we should threat this as a "pure function" to start having the same behaviour and continuing passing for the sortGrid to prevent bug in edge cases until we can plan a migration to a better gridSorting that probably would be do it by "merging the Grid and the Grid Base" as you said

File: src/components/FixedGrid/utils.ts (hunk 2 above)
Comment (RodriSanchez1) [reply src/components/FixedGrid/utils.ts]: Something like `getDeprecatedOrderedPages` ?

**Comment by RodriSanchez1** [comment]
Okay, thanks for the explanation. It makes sense. One think that I don't like is to repeat the sorting on the chunk function and after that in the `sortGrid` , but if the idea is to refactor the `GridBase` soon it can be okay.

Regarding to the PR, I made a basic test: Render a fixed board using the old chunks and the new one. This should render the same pages as it supports the old  deprecated behaviour . 

As you can see in the following image the rendered pages are not the same. 
image

The attached image is not accurate to the following reproduction steps, but you will get the same:

1- Clean browser cache
2- Go to PicseePal board
3- Remove a row
4- See the rendered pages
5- Go to the code and make the changes to use the old chunk function
6- Compare the rendered pages with the previous ones

The exported are different also, it think it use the old behaviour to generate the exported pdf

Sorry for the late response. Is a complex functionallity and a extensive test should be done before merge it to master. 

I like the idea to refactor this,

File: src/components/FixedGrid/utils.ts (hunk 6 above)
Comment (tomivm) [reply src/components/FixedGrid/utils.ts]: Awesome! I saw and old documentation

File: src/components/FixedGrid/utils.ts (hunk 2 above)
Comment (tomivm) [reply src/components/FixedGrid/utils.ts]: Perfect!

File: src/components/FixedGrid/utils.ts (hunk 7 above)
Comment (tomivm) [reply src/components/FixedGrid/utils.ts]: Nice suggestion! thanks

**Comment by tomivm** [comment]
Hey Rodri! Awesome feedback! That is the valuable feedback that I was looking for. 
As you said this is a complex functionality and for that your feedback is important. Also for that the time that we take to review PRs directly impact in the continuos integration that our team is trying to archive! 
If the review is delayed the complex of the issue cause developer have to invert time to remember the code, prepare the enviroment causing it's first read of the review have less context and more tasks to do.
It's okey to take time to make reviews with dedication but please the next time that **a partner is awaiting something from you** don't spent your time in another issue with low priority until you finish supporting the team work.
Thanks for dedicate the time to this! you found a case that I never thought for this. 
**Users make a change in a new version of the app and have other devices with old versions**
Also it represent your worry of "I don't like is to repeat the sorting on the chunk function and after that in the sortGrid"
This makes me think that if we want to improve sorting and we can dedicate a full PR to intent to move the sorting logic up
For that to solve this and also solve the problem that only occurs when a column or a row is removed I move the logic up to the board container and the sort function is only called inside `handleAddRemoveRow` and `handleAddRemoveColumn`
This fix the order of the tileList ensuring old versions continue showing the exact same board than a new version and ensure that this changes only affects the functionality that have the issue and avoid unnecessary changes to our Grid component that caused the unnecessary double sorting when props `order` and `tiles` changes.
As you said this functionality needs an extensive test. Please review it as soon as possible to be integrated before the testing process pre-deploy planed for this week! Also i contacted a Speech therapist that work with Cboard for long time to test all the improvements that we make the past week.
Sadly we don't know when we can dedicate a full week to Cboard again to improve the sortGrid process and this change drastically improve the break of user's boards during the use of a feature that is in master!!

Again, Thanks for your feedback and support that allow Cboard to continue growing and improving day by day 🥳 
Let me know your thoughts please!

**Review by RodriSanchez1 — APPROVED** [review]
Lot of things happened.  I thinking what side effectes we can get if the tiles list changes. For now a I was not able to find anything that can breaks. 

This is a good provisional solution, well done 🤘! 

The referenced issue is not longer apropiate for this PR :(

**Comment by tomivm** [comment]
Yes I find an old issue about this. The issue of the chunking issue was only mentioned
Happy of launching this together with all the improvements that we make in our next version!
