### PR TITLE
Fix/cloud voices on apple

### LINKED ISSUE #1398: cloud voices not work on IOS Apple devices
User Agent of IOS blocks cloud voices play

### PR DESCRIPTION
**Pull request by tomivm**
#1398

### CODE REVIEW

File: src/constants.js [hunk 1]
```diff
@@ -31,3 +31,8 @@ export const ADTEST_AVAILABLE =
 export const ADSENSE_CLIENT = 'ca-pub-7162313874228987';
 
 export const ADD_SLOT_SETTINGS_TOP = '5250438005';
+
+export const IS_BROWSING_FROM_APPLE = (() => {
```
Comment (RodriSanchez1) [inline src/constants.js]: I think thath you can do directly like this:  `export const IS_BROWSING_FROM_APPLE =/iPad|iPhone|iPod|Mac/.test(navigator.userAgent)`

**Review by martinbedouret — APPROVED** [review]
